
trigger:
  branches:
    include:
    - dev
pool:
  vmImage: 'windows-latest'

parameters:
  - name: run_scripts
    type: boolean
    default: false
  - name: cycles
    type: object
    default:
        - dev

stages:

# This is the start of building, testing and publishing.
- template: templates/all-stages.yml
  parameters:
    runScripts: ${{ parameters.run_scripts }}
    cycles: ${{ parameters.cycles }}
