
trigger:
  branches:
    include:
    - main
    - release/*
  tags:
    include:
    - 'v*'
pool:
  vmImage: 'windows-latest'

parameters:
  - name: run_scripts
    type: boolean
    default: true
  - name: cycles
    type: object
    default:
        - main
        - release

stages:

# This is the start of building, testing and publishing.
- template: templates/all-stages.yml
  parameters:
    runScripts: ${{ parameters.run_scripts }}
    cycles: ${{ parameters.cycles }}
